// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/meta-bps/CrmClientes.tsx": () => import("../components/mockups/meta-bps/CrmClientes.tsx"),
  "./components/mockups/meta-bps/CrmConversacion.tsx": () => import("../components/mockups/meta-bps/CrmConversacion.tsx")
};
